# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "About"
  url = "#about"
  weight = 10

[[menu.main]]
  name = "Blog"
  url = "#posts"
  weight = 20

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 30

[[menu.main]]
  name = "Publications"
  url = "#publications"
  weight = 40

[[menu.main]]
  name = "Resources"
  url = "#"
  weight = 50
  hasChildren = true

[[menu.main]]
  parent = "Resources"
  name = "Neuropsychology"
  url = "/neuropsychology/"
  weight = 55

[[menu.main]]
  parent = "Resources"
  name = "Neuroscience"
  url = "/neuroscience/"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70

# [[main]]
#   name = "Contact"
#   url = "#contact"
#   weight = 70
